import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "./globals.css";
import ClientProvider from "@/provider/ClientProvider";

const geistSans = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "digitalEICH Frontend Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
        suppressHydrationWarning
      >
        <ClientProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </ClientProvider>
      </body>
    </html>
  );
}
